-- ===========================================================================
-- opening_hours: re-sync the identity sequence, and split overnight slots
-- Rasa Route / odtmtukexckfjbuqkxyo - 2026-09-12
-- ===========================================================================
--
-- APPLIED. This ran against the live database as migration
-- `opening_hours_resync_identity_and_split_overnight`, and the numbers in the
-- comments below are what it actually did, not estimates.
--
-- Wrap in BEGIN/COMMIT if you run it by hand; the Supabase migration runner
-- already runs it in one transaction.
--
-- ---------------------------------------------------------------------------
-- THE SCHEMA, AS INSPECTED
-- ---------------------------------------------------------------------------
--   opening_hours_id  bigint  GENERATED BY DEFAULT AS IDENTITY, primary key
--   day               public.day enum: Monday .. Sunday
--   opening_time      time, nullable
--   closing_time      time, nullable
--   landmark_id       bigint -> submitted_landmark, nullable
--   restaurant_id     bigint -> restaurant, nullable
--   status            public.status_enum: open | closed | unknown
--
--   unique (restaurant_id, day, opening_time, closing_time) NULLS NOT DISTINCT
--          WHERE restaurant_id is not null          <- no landmark equivalent
--   no triggers
--
-- ---------------------------------------------------------------------------
-- THE TWO PROBLEMS
-- ---------------------------------------------------------------------------
-- 1. The identity sequence was BEHIND the table. `GENERATED BY DEFAULT`
--    means an explicit-id insert does not advance the sequence, so a bulk load
--    that supplied ids left it at 303,716 against a max id of 303,722. The
--    next six inserts that let the identity generate would have collided with
--    rows that already existed - the reported
--        duplicate key value violates unique constraint "opening_hours_pkey"
--
-- 2. An overnight slot was one row whose closing time is EARLIER than its
--    opening time - `Monday 22:00-02:00` - so every reader had to know to wrap
--    it round midnight. Split into two rows it is ordinary data.
--
-- ---------------------------------------------------------------------------
-- WHAT IT FOUND, AND DID
-- ---------------------------------------------------------------------------
--   116,322 rows before, 124,383 after - exactly +8,061, nothing deleted
--    15,221 overnight rows, every one of them a restaurant
--     7,160 closed exactly at midnight -> closing time becomes 24:00 and NO
--           second row is written, because `00:00-00:00` is not a slot
--     8,061 needed a second row; none collided with a slot already present,
--           and all 8,061 were distinct from each other
--         9 rows already ended at 24:00 - left alone
--         2 rows have opening = closing, which is not `<` - left alone
--     8,039 rows have a null time - left alone
--         0 overnight rows remain
--
--   Worked example, restaurant "Pasembur King (Hussain)":
--       before   Sunday 11:30-00:30   Monday 11:45-00:15
--       after    Sunday 11:30-24:00   Monday 00:00-00:30
--                Monday 11:45-24:00   Tuesday 00:00-00:15
--   Both of Monday's slots survive, which is the point of doing this per row.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. The sequence
-- ---------------------------------------------------------------------------
-- `pg_get_serial_sequence` rather than the sequence's literal name, so this
-- stays correct if the sequence is ever renamed. `true` for is_called means
-- the next value handed out is max + 1.
select setval(
  pg_get_serial_sequence('public.opening_hours', 'opening_hours_id'),
  (select coalesce(max(opening_hours_id), 0) from public.opening_hours),
  true
);


-- ---------------------------------------------------------------------------
-- 2. The second half of every overnight slot
-- ---------------------------------------------------------------------------
-- The next day is read off the enum itself - `array_position` into
-- `enum_range`, wrapped with a modulo - rather than a seven-branch CASE over
-- hard-coded labels. Sunday wraps to Monday, and nothing breaks if a label is
-- renamed or the enum is reordered.
--
-- Three independent guards make this safe to run again:
--   * `distinct` collapses two overnight slots that would produce the same
--     tail row;
--   * `not exists` skips a tail already in the table;
--   * `on conflict do nothing` is the backstop for the restaurant unique
--     index (and the only protection landmarks would get, since they have no
--     equivalent index - see the note at the end).
-- A second run is a no-op for a fourth reason as well: after step 3 no row
-- satisfies `closing_time < opening_time` any more. Verified: a second pass
-- inserts 0 rows and updates 0 rows.
--
-- The id is left to the identity, which step 1 has just made safe.
with overnight as (
  select distinct
         (enum_range(null::public.day))[
           (array_position(enum_range(null::public.day), oh.day)
             % array_length(enum_range(null::public.day), 1)) + 1 ] as tail_day,
         oh.closing_time,
         oh.restaurant_id,
         oh.landmark_id,
         oh.status
    from public.opening_hours oh
   where oh.opening_time is not null
     and oh.closing_time is not null
     and oh.closing_time < oh.opening_time
     -- A slot that closes at midnight has no next-day half.
     and oh.closing_time > time '00:00:00'
)
insert into public.opening_hours (
  day, opening_time, closing_time, restaurant_id, landmark_id, status
)
select o.tail_day, time '00:00:00', o.closing_time,
       o.restaurant_id, o.landmark_id, o.status
  from overnight o
 where not exists (
   select 1
     from public.opening_hours e
    where e.day = o.tail_day
      and e.opening_time = time '00:00:00'
      and e.closing_time = o.closing_time
      -- `is not distinct from`, so the null side of the pair matches too: a
      -- landmark row has a null restaurant_id, and `=` against null is never
      -- true, which would make this guard silently useless for landmarks.
      and e.restaurant_id is not distinct from o.restaurant_id
      and e.landmark_id  is not distinct from o.landmark_id
 )
on conflict do nothing;


-- ---------------------------------------------------------------------------
-- 3. The first half now ends at the end of the day
-- ---------------------------------------------------------------------------
-- Postgres `time` accepts 24:00:00, which is exactly what is meant: this slot
-- runs to the end of this day and the row inserted above carries the rest.
--
-- The rows inserted in step 2 open at 00:00 and close later, so they do not
-- satisfy this predicate and are not touched by it. Order matters the other
-- way round, though: the insert has to read the overnight rows BEFORE this
-- update rewrites them, or the tail times are gone.
update public.opening_hours
   set closing_time = time '24:00:00'
 where opening_time is not null
   and closing_time is not null
   and closing_time < opening_time;


-- ===========================================================================
-- VERIFICATION - all of these were run and all of them passed
-- ===========================================================================
--
--   -- rows: 116,322 + 8,061 = 124,383
--   select count(*) from public.opening_hours;
--
--   -- no overnight row left
--   select count(*) from public.opening_hours
--    where opening_time is not null and closing_time is not null
--      and closing_time < opening_time;                        -- expect 0
--
--   -- the sequence is ahead of the data again
--   select (select max(opening_hours_id) from public.opening_hours) as max_id,
--          (select last_value from public.opening_hours_opening_hours_id_seq);
--
--   -- nothing lost
--   select count(*) from public.opening_hours
--    where restaurant_id is null and landmark_id is null;      -- expect 0
--   select count(*) from public.opening_hours
--    where opening_time is null or closing_time is null;       -- expect 8,039
--
--
-- ===========================================================================
-- TWO THINGS LEFT ON THE TABLE, DELIBERATELY
-- ===========================================================================
--
-- 1. LANDMARKS HAVE NO UNIQUE INDEX. Restaurants are protected by
--    `opening_hours_restaurant_schedule_uniq`; the landmark side has nothing,
--    so duplicate landmark slots can be inserted by any path, not just this
--    one. There are 40 landmark rows and none of them is overnight, so this
--    migration was never at risk - but the gap is real. The fix, once the
--    existing rows are confirmed duplicate-free:
--
--      create unique index concurrently if not exists
--        opening_hours_landmark_schedule_uniq
--        on public.opening_hours (landmark_id, day, opening_time, closing_time)
--        nulls not distinct
--        where landmark_id is not null;
--
--    `concurrently` cannot run inside a transaction, which is why it is not
--    part of the migration above.
--
-- 2. READERS NOW SEE 24:00. Anything that formats these rows will print
--    "24:00" where it used to print "00:00", and anything that still contains
--    wrap-around logic for `closing < opening` now has dead code in it. The
--    unapplied `hours_overlap_meal` / `open_for_meal` functions in
--    `rasa_route_migrations_2026-09-11.sql` expand wrapping intervals by hand;
--    that half of them is now unnecessary, though harmless.


-- ===========================================================================
-- ADDENDUM, same day: compact the primary key to 1 .. count(*)
-- ===========================================================================
-- Applied as `opening_hours_compact_ids_from_one`.
--
-- After the split the table held 124,383 rows numbered 16 .. 311,783 - 187,400
-- numbers of gap, left by bulk loads and by a client that supplied its own ids.
--
-- SAFE because **nothing references `opening_hours_id`**: `pg_constraint` has
-- no foreign key whose `confrelid` is this table. The app reads the id (it
-- becomes `OpeningHour.id`, and it is the `orderBy` key that makes
-- `selectEvery` paging deterministic) but never stores it anywhere else, so a
-- renumber is invisible once rows are refetched.
--
-- WHY TWO PASSES: `opening_hours_pkey` is NOT deferrable, so uniqueness is
-- checked row by row as the update runs. Assigning 1..n directly collides the
-- moment a new id lands on an old one not yet rewritten - row 20 becoming 5
-- while the real 5 is still there. So shift clear of the range first, then come
-- back down.

-- Pass 1: lift every id above the old maximum, so no new value can hit an
-- existing one. The offset is read from the table, not typed.
update public.opening_hours
   set opening_hours_id = opening_hours_id
     + (select coalesce(max(opening_hours_id), 0) from public.opening_hours);

-- Pass 2: back down as 1 .. count(*). Every new value is far below the shifted
-- block, so again nothing collides. Ordering by the (uniformly shifted) id
-- preserves the original relative order exactly.
with renumbered as (
  select opening_hours_id as old_id,
         row_number() over (order by opening_hours_id) as new_id
    from public.opening_hours
)
update public.opening_hours oh
   set opening_hours_id = r.new_id
  from renumbered r
 where oh.opening_hours_id = r.old_id;

-- The sequence follows the data: next generated id is count + 1.
select setval(
  pg_get_serial_sequence('public.opening_hours', 'opening_hours_id'),
  (select coalesce(max(opening_hours_id), 0) from public.opening_hours),
  true
);

-- Two full-table rewrites leave every row version behind. Not optional, and it
-- cannot run inside the transaction:
--   vacuum (analyze) public.opening_hours;

-- ---------------------------------------------------------------------------
-- VERIFIED
-- ---------------------------------------------------------------------------
--   rows 124,383 | min 1 | max 124,383 | distinct 124,383 | gap 0
--   sequence last_value 124,383, is_called true -> next id 124,384
--
--   Lossless: an md5 over every column EXCEPT the id, aggregated in sorted
--   order, is byte-identical before and after -
--       4efcefa73a817235af18c931133e81fc
--
-- ---------------------------------------------------------------------------
-- THE CAUSE, FIXED IN THE APP AT THE SAME TIME
-- ---------------------------------------------------------------------------
-- `SubmittedLandmarkRepository._insertOpeningHours` read `max(id) + 1` and
-- passed `opening_hours_id` explicitly on every insert. An explicit value does
-- not advance an identity's sequence, so each landmark submission left the
-- sequence one further behind - and it was a race besides, since `max + 1` read
-- by two tourists at once is the same number twice.
--
-- The Dart now omits the column and lets the identity generate. Without that,
-- this renumber would have walked straight back out of step.
--
-- `_nextId` is still correct for `submitted_landmark.landmark_id`, which is a
-- plain bigint with no identity and no sequence at all - checked, not assumed.
